echo "CAAGCAACGCAAAGAUUUUAGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGGUGCUUUUUU" | RNAfold  --noPS --MEA --noLP
echo "CAAGCAACGCAAAGAUUUUAGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGGUGCUUUUUU" | RNAfold  --noPS --MEA --noLP
echo "CAAGCAACGCAAAGAUUUUAGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGGUGCUUUUUU" | RNAfold  --noPS --MEA --noLP
echo "CAAGCAACGCAAAGAUUUUAGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGGUGCUUUUUU" | RNAfold  --noPS --MEA --noLP
echo "CAAGCAACGCAAAGAUUUUAGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGGUGCUUUUUU" | RNAfold  --noPS --MEA --noLP

echo "CAAGCAACGCAAAGAUUUUAGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGGUGCUUUUUU" | RNAfold  --noPS --MEA --noLP
echo "CAAGCAACGCAAAGAUUUUAGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGGUGCUUUUUU" | RNAfold  --noPS --MEA --noLP
echo "CAAGCAACGCAAAGAUUUUAGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGGUGCUUUUUU" | RNAfold  --noPS --MEA --noLP
echo "CAAGCAACGCAAAGAUUUUAGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGGUGCUUUUUU" | RNAfold  --noPS --MEA --noLP
echo "CAAGCAACGCAAAGAUUUUAGUUUUAGAGCUAGAAAUAGCAAGUUAAAAUAAGGCUAGUCCGUUAUCAACUUGAAAAAGUGGCACCGAGUCGGUGGUGCUUUUUU" | RNAfold  --noPS --MEA --noLP
